# -*- coding: utf-8 -*-
"""Despliegue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EOLlzO3Z0ZzIzzYDGU6wnoNMcpajSFSi

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-class.pkl'
model_rf, labelencoder,variables = pickle.load(open(filename, 'rb'))

#Cargamos los datos futuros
#data = pd.read_csv("registros_futuros.csv")
#data.head()

#Interfaz gráfica

#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de Parto Exitoso en Hembras Porcinas')

NUMERO_PARTO = st.slider('Número de parto', min_value=2, max_value=19, value=4, step=1)
PROMEDIO_VIVOS_ANTERIORES = st.slider('Promedio de vivos anteriores', min_value=0.0, max_value=31.0, value=13.0, step=0.1)
TOTAL_MUERTOS_ANTERIORES = st.slider('Total de muertos anteriores', min_value=0, max_value=35, value=2, step=1)
RETORNOS_ACUMULADOS = st.slider('Retornos acumulados', min_value=0, max_value=9, value=0, step=1)

# Dataframe
datos = [[NUMERO_PARTO, PROMEDIO_VIVOS_ANTERIORES, TOTAL_MUERTOS_ANTERIORES, RETORNOS_ACUMULADOS]]
data = pd.DataFrame(datos, columns=['NUMERO_PARTO', 'PROMEDIO_VIVOS_ANTERIORES', 'TOTAL_MUERTOS_ANTERIORES', 'RETORNOS_ACUMULADOS'])

"""# **Predicciones**"""

#Hacemos la predicción con el Tree
Y_pred = model_rf.predict(data)
print(Y_pred)

data['Prediccion'] = Y_pred
data['Prediccion'] = data['Prediccion'].map({0: 'EXITOSO', 1: 'NO_EXITOSO'})
data.head()

data

st.warning("El modelo tiene una precisión del 61.6%, lo que equivale a un error del 38.4%")